export const CONFIRMATION_EMAIL_REDIRECT = process.env.NEXT_PUBLIC_ENVIRONMENT === 'production' ? process.env.NEXT_PUBLIC_PRODUCTION_CONFIRMATION_EMAIL_REDIRECT : process.env.NEXT_PUBLIC_DEVELOPMENT_CONFIRMATION_EMAIL_REDIRECT;

export const API = process.env.NEXT_PUBLIC_ENVIRONMENT === 'production' ? process.env.NEXT_PUBLIC_PRODUCTION_API : process.env.NEXT_PUBLIC_DEVELOPMENT_API;

export const FORGOT_PASSWORD_REDIRECT = process.env.NEXT_PUBLIC_ENVIRONMENT === 'production' ? process.env.NEXT_PUBLIC_PRODUCTION_FORGOT_PASSWORD_REDIRCT : process.env.NEXT_PUBLIC_DEVELOPMENT_FORGOT_PASSWORD_REDIRCT

export const APP_NAME = process.env.NEXT_PUBLIC_APP_NAME;

export const DOMAIN = process.env.NEXT_PUBLIC_ENVIRONMENT === 'production' ? process.env.NEXT_PUBLIC_PRODUCTION_DOMAIN : process.env.NEXT_PUBLIC_DEVELOPMENT_DOMAIN;